# SPDX-License-Identifier: MPL-2.0
#
#  NaviServer with PostgreSQL client support.
#  Install "nsdbpg" on top of the "naviserver" image
#
ARG RELEASE_TAG="latest"
ARG LOCAL_TAG=""
ARG base_image=gustafn/naviserver:${RELEASE_TAG}-alpine${LOCAL_TAG}
FROM ${base_image}

# Make sure to refresh the script (for development only)
COPY get-naviserver-modules.sh /scripts


ARG system_pkgs=""
RUN  apk add --no-cache libpq $apk_pkgs  && dev_packages="git musl-dev gcc make zlib-dev libpq-dev curl bash"  && apk add ${dev_packages} \
   && sh /scripts/get-naviserver-modules.sh -m nsdbpg -i \
   && apk del ${dev_packages}


